lr: 1e-4
lr_decay_step:

log_train_metrics: false
log_train_visual: false
log_visual_every_n_epoch: 10

trainer:
    max_epochs: 500
    log_every_n_steps: 10
    check_val_every_n_epoch: 10
    fast_dev_run: False
    limit_train_batches: 1.0
    limit_val_batches: 1.0
    resume_from_checkpoint: